### ISSUE TITLE
Align image

### ISSUE THREAD

**Issue by lostfiddler** [artisticat1/obsidian-tikzjax#26]
Just downloaded this plugin and I'm pretty new to latex, so I don't know if there's an obvious answer to this question. I'm trying to align the image generated from `\begin{tikzpicture}` to the left, not just nodes or equations but the whole image. I've searched on google but none of the results helped. Any response would be appreciated, thanks.

**Comment by lostfiddler** [comment]
Figured out a solution. Had to add a css snippet that removed the left margin from the svg block:
```css
.markdown-rendered .block-language-tikz svg {
    margin-left: 0;
}
```
